### ISSUE TITLE
READ処理とUPDATE処理をREST API化する

### ISSUE THREAD

**Issue by Omi354** [Omi354/portfolio-student-management#23]
## 全体像の把握・目的
- 全体像
	- Controllerのアノテーションを修正
	- Controllerの返り値を変更、修正
	- 不要なHTMLの削除

- タスク、課題の目的
	- REST APIに適した返り値を指定する
	- Postmanを使ったAPI作成の練習

## 完了条件の言語化
- GetMappingとPatchMappingのAPI化と手動テストの実施

## 事前条件の確認
- Thymeleafを使ったCRUD処理が実装されている
- REST APIの考え方について理解できている

## タスク分解
- 合計：1時間35分
	- 受講生情報一覧表示の修正：10分
	- 受講コース情報一覧表示の修正：10分
	- newStudentの削除：5分
	- 単一受講生表示の修正：10分
	- 受講生更新機能の修正：10分
	- HTMLの削除：10分
	- 上記のテストを実施：30分
	- リファクタリング：10分
	
## 予実の確認
- 予定： 1時間15分
- 実績： 25分
	- 受講生情報一覧表示の修正：10分　→　5分
	- 受講コース情報一覧表示の修正：10分　→　5分
	- newStudentの削除：5分　→　0分
	- 単一受講生表示の修正：10分　→　5分
	- 受講生更新機能の修正：10分　→　10分
	- HTMLの削除：10分　→　0分
	- 上記のテストを実施：30分　→　0分　
		- 都度実施
	- リファクタリング：10分　→　0分

**Comment by lattaai12** [comment]
Hello, I tried to solve the issue.

This is what I did:

Modified StudentController to return JSON responses instead of view names. Removed Thymeleaf-related code and updated mappings to be RESTful.

You can review changes in this commit: https://github.com/lattaai12/Omi354-portfolio-student-management-23/commit/eacffebd81111805e502d4369923b522dc13051a.


> [!CAUTION]
> Disclaimer: The commit was created by Latta AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---
This issue was tried to solve for free by Latta AI - https://latta.ai/ourmission

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Omi354** [comment]
完了しました。実績詳細をdescriptionに記述しました。

## 振り返り

- 乖離： -50分
- 主な要因
    - はじめてのタスクもあったので長めに見積もった
- NA
    - 手をたくさん動かして自分の実装スピードを把握していく
